[package]
name = "factory"
version = "1.0.0"
authors = []

[addresses]
factory = "2582bc98b3fdebf431729eac9bbc9b3a52647a3471c552571c2c9259e4ab2027"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
