CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"rank" integer DEFAULT 1 NOT NULL,
	"username" text NOT NULL,
	"description" text NOT NULL,
	"avatar" text,
	"email" text NOT NULL,
	"aptos_address" text NOT NULL,
	"join_date" timestamp DEFAULT now() NOT NULL,
	"followers" integer DEFAULT 0 NOT NULL,
	"following" integer DEFAULT 0 NOT NULL,
	"videos" integer DEFAULT 0 NOT NULL,
	"shorts" integer DEFAULT 0 NOT NULL,
	"views" integer DEFAULT 0 NOT NULL,
	"total_donation" integer DEFAULT 0 NOT NULL,
	"total_donation_count" integer DEFAULT 0 NOT NULL,
	"tags" jsonb,
	"social" jsonb,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_aptos_address_unique" UNIQUE("aptos_address")
);
