/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes";
import { Route as ReelsImport } from "./routes/reels";
import { Route as LivestreamImport } from "./routes/livestream";
import { Route as ChallengesImport } from "./routes/challenges";
import { Route as NftsImport } from "./routes/nfts";;
import { Route as StudioImport } from "./routes/studio";
import { Route as LiveDetailsImport } from "./routes/live/$username";
import { Route as ProfileImport } from "./routes/u/$username";
import { Route as SearchImport } from "./routes/search";
import { Route as ShortVideoImport } from "./routes/s/$videoId";
import { Route as VideoImport } from "./routes/v/$videoId";
import { Route as WalletImport } from "./routes/wallet";
import { Route as CallbackImport } from "./routes/callback";
import { Route as ListTaskImport } from "./routes/tasks";

// Create/Update Routes
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const ReelsRoute = ReelsImport.update({
  id: "/reels",
  path: "/reels",
  getParentRoute: () => rootRoute,
} as any);

const LivestreamRoute = LivestreamImport.update({
  id: "/livestream",
  path: "/livestream",
  getParentRoute: () => rootRoute,
} as any);

const ChallengesRoute = ChallengesImport.update({
  id: "/challenges",
  path: "/challenges",
  getParentRoute: () => rootRoute,
} as any);

const NftsRoute = NftsImport.update({
  id: "/nfts",
  path: "/nfts",
  getParentRoute: () => rootRoute,
} as any);

const StudioRoute = StudioImport.update({
  id: "/studio",
  path: "/studio",
  getParentRoute: () => rootRoute,
} as any);

const LiveDetailsRoute = LiveDetailsImport.update({
  id: "/live/$username",
  path: "/live/$username",
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  id: "/u/$username",
  path: "/u/$username",
  getParentRoute: () => rootRoute,
} as any);

const SearchRoute = SearchImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRoute,
} as any);

const ShortVideoRoute = ShortVideoImport.update({
  id: "/s/$videoId",
  path: "/s/$videoId",
  getParentRoute: () => rootRoute,
} as any);

const VideoRoute = VideoImport.update({
  id: "/v/$videoId",
  path: "/v/$videoId",
  getParentRoute: () => rootRoute,
} as any);

const WalletRoute = WalletImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => rootRoute,
} as any);

const CallbackRoute = CallbackImport.update({
  id: "/callback",
  path: "/callback",
  getParentRoute: () => rootRoute,
} as any);

const ListTaskRoute = ListTaskImport.update({
  id: "/list_task",
  path: "/list_task",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/reels": {
      id: "/reels";
      path: "/reels";
      fullPath: "/reels";
      preLoaderRoute: typeof ReelsRoute;
      parentRoute: typeof rootRoute;
    };
    "/livestream": {
      id: "/livestream";
      path: "/livestream";
      fullPath: "/livestream";
      preLoaderRoute: typeof LivestreamRoute;
      parentRoute: typeof rootRoute;
    };
    "/challenges": {
      id: "/challenges";
      path: "/challenges";
      fullPath: "/challenges";
      preLoaderRoute: typeof ChallengesRoute;
      parentRoute: typeof rootRoute;
    };
    "/nfts": {
      id: "/nfts";
      path: "/nfts";
      fullPath: "/nfts";
      preLoaderRoute: typeof NftsRoute;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRoute;
      parentRoute: typeof rootRoute;
    };
    "/studio": {
      id: "/studio";
      path: "/studio";
      fullPath: "/studio";
      preLoaderRoute: typeof StudioRoute;
      parentRoute: typeof rootRoute;
    };
    "/live/$username": {
      id: "/live/$username";
      path: "/live/$username";
      fullPath: "/live/$username";
      preLoaderRoute: typeof LiveDetailsRoute;
      parentRoute: typeof rootRoute;
    };
    "/u/$username": {
      id: "/u/$username";
      path: "/u/$username";
      fullPath: "/u/$username";
      preLoaderRoute: typeof ProfileRoute;
      parentRoute: typeof rootRoute;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRoute;
      parentRoute: typeof rootRoute;
    };
    "/s/$videoId": {
      id: "/s/$videoId";
      path: "/s/$videoId";
      fullPath: "/s/$videoId";
      preLoaderRoute: typeof ShortVideoRoute;
      parentRoute: typeof rootRoute;
    };
    "/v/$videoId": {
      id: "/v/$videoId";
      path: "/v/$videoId";
      fullPath: "/v/$videoId";
      preLoaderRoute: typeof VideoRoute;
      parentRoute: typeof rootRoute;
    };
    "/wallet": {
      id: "/wallet";
      path: "/wallet";
      fullPath: "/wallet";
      preLoaderRoute: typeof WalletRoute;
      parentRoute: typeof rootRoute;
    };
    "/callback": {
      id: "/callback";
      path: "/callback";
      fullPath: "/callback";
      preLoaderRoute: typeof CallbackRoute;
      parentRoute: typeof rootRoute;
    };
    "/list_task": {
      id: "/list_task";
      path: "/list_task";
      fullPath: "/list_task";
      preLoaderRoute: typeof ListTaskRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/reels": typeof ReelsRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/studio": typeof StudioRoute;
  "/live/$username": typeof LiveDetailsRoute;
  "/u/$username": typeof ProfileRoute;
  "/search": typeof SearchRoute;
  "/s/$videoId": typeof ShortVideoRoute;
  "/v/$videoId": typeof VideoRoute;
  "/wallet": typeof WalletRoute;
  "/callback": typeof CallbackRoute;
  "/list_task": typeof ListTaskRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/reels": typeof ReelsRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/studio": typeof StudioRoute;
  "/live/$username": typeof LiveDetailsRoute;
  "/u/$username": typeof ProfileRoute;
  "/search": typeof SearchRoute;
  "/s/$videoId": typeof ShortVideoRoute;
  "/v/$videoId": typeof VideoRoute;
  "/wallet": typeof WalletRoute;
  "/callback": typeof CallbackRoute;
  "/list_task": typeof ListTaskRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/reels": typeof ReelsRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/studio": typeof StudioRoute;
  "/live/$username": typeof LiveDetailsRoute;
  "/u/$username": typeof ProfileRoute;
  "/search": typeof SearchRoute;
  "/s/$videoId": typeof ShortVideoRoute;
  "/v/$videoId": typeof VideoRoute;
  "/wallet": typeof WalletRoute;
  "/callback": typeof CallbackRoute;
  "/list_task": typeof ListTaskRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/reels"
    | "/livestream"
    | "/challenges"
    | "/nfts"
    | "/profile"
    | "/studio"
    | "/live/$username"
    | "/u/$username"
    | "/search"
    | "/s/$videoId"
    | "/v/$videoId"
    | "/wallet"
    | "/callback"
    | "/list_task"
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/reels" | "/livestream" | "/challenges" | "/nfts" | "/profile" | "/studio" | "/live/$username" | "/u/$username" | "/search" | "/s/$videoId" | "/v/$videoId" | "/wallet" | "/callback";
  id:
    | "__root__"
    | "/"
    | "/reels"
    | "/livestream"
    | "/challenges"
    | "/nfts"
    | "/profile"
    | "/studio"
    | "/live/$username"
    | "/u/$username"
    | "/search"
    | "/s/$videoId"
    | "/v/$videoId"
    | "/wallet"
    | "/callback"
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ReelsRoute: typeof ReelsRoute;
  LivestreamRoute: typeof LivestreamRoute;
  ChallengesRoute: typeof ChallengesRoute;
  NftsRoute: typeof NftsRoute;
  ProfileRoute: typeof ProfileRoute;
  StudioRoute: typeof StudioRoute;
  LiveDetailsRoute: typeof LiveDetailsRoute;
  ProfileRoute: typeof ProfileRoute;
  SearchRoute: typeof SearchRoute;
  ShortVideoRoute: typeof ShortVideoRoute;
  VideoRoute: typeof VideoRoute;
  WalletRoute: typeof WalletRoute;
  CallbackRoute: typeof CallbackRoute;
  ListTaskRoute: typeof ListTaskRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReelsRoute: ReelsRoute,
  LivestreamRoute: LivestreamRoute,
  ChallengesRoute: ChallengesRoute,
  NftsRoute: NftsRoute,
  ProfileRoute: ProfileRoute,
  StudioRoute: StudioRoute,
  LiveDetailsRoute: LiveDetailsRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  ShortVideoRoute: ShortVideoRoute,
  VideoRoute: VideoRoute,
  WalletRoute: WalletRoute,
  CallbackRoute: CallbackRoute,
  ListTaskRoute: ListTaskRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>(); 