/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexImport } from "./routes";
import { Route as VideosImport } from "./routes/videos";
import { Route as LivestreamImport } from "./routes/livestream";
import { Route as ChallengesImport } from "./routes/challenges";
import { Route as NftsImport } from "./routes/nfts";
import { Route as ProfileImport } from "./routes/profile";
import { Route as UploadImport } from "./routes/upload";

// Create/Update Routes
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const VideosRoute = VideosImport.update({
  id: "/videos",
  path: "/videos",
  getParentRoute: () => rootRoute,
} as any);

const LivestreamRoute = LivestreamImport.update({
  id: "/livestream",
  path: "/livestream",
  getParentRoute: () => rootRoute,
} as any);

const ChallengesRoute = ChallengesImport.update({
  id: "/challenges",
  path: "/challenges",
  getParentRoute: () => rootRoute,
} as any);

const NftsRoute = NftsImport.update({
  id: "/nfts",
  path: "/nfts",
  getParentRoute: () => rootRoute,
} as any);

const ProfileRoute = ProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRoute,
} as any);

const UploadRoute = UploadImport.update({
  id: "/upload",
  path: "/upload",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/videos": {
      id: "/videos";
      path: "/videos";
      fullPath: "/videos";
      preLoaderRoute: typeof VideosRoute;
      parentRoute: typeof rootRoute;
    };
    "/livestream": {
      id: "/livestream";
      path: "/livestream";
      fullPath: "/livestream";
      preLoaderRoute: typeof LivestreamRoute;
      parentRoute: typeof rootRoute;
    };
    "/challenges": {
      id: "/challenges";
      path: "/challenges";
      fullPath: "/challenges";
      preLoaderRoute: typeof ChallengesRoute;
      parentRoute: typeof rootRoute;
    };
    "/nfts": {
      id: "/nfts";
      path: "/nfts";
      fullPath: "/nfts";
      preLoaderRoute: typeof NftsRoute;
      parentRoute: typeof rootRoute;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRoute;
      parentRoute: typeof rootRoute;
    };
    "/upload": {
      id: "/upload";
      path: "/upload";
      fullPath: "/upload";
      preLoaderRoute: typeof UploadRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/videos": typeof VideosRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/upload": typeof UploadRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/videos": typeof VideosRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/upload": typeof UploadRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/videos": typeof VideosRoute;
  "/livestream": typeof LivestreamRoute;
  "/challenges": typeof ChallengesRoute;
  "/nfts": typeof NftsRoute;
  "/profile": typeof ProfileRoute;
  "/upload": typeof UploadRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/videos"
    | "/livestream"
    | "/challenges"
    | "/nfts"
    | "/profile"
    | "/upload"
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/videos" | "/livestream" | "/challenges" | "/nfts" | "/profile" | "/upload";
  id:
    | "__root__"
    | "/"
    | "/videos"
    | "/livestream"
    | "/challenges"
    | "/nfts"
    | "/profile"
    | "/upload"
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  VideosRoute: typeof VideosRoute;
  LivestreamRoute: typeof LivestreamRoute;
  ChallengesRoute: typeof ChallengesRoute;
  NftsRoute: typeof NftsRoute;
  ProfileRoute: typeof ProfileRoute;
  UploadRoute: typeof UploadRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VideosRoute: VideosRoute,
  LivestreamRoute: LivestreamRoute,
  ChallengesRoute: ChallengesRoute,
  NftsRoute: NftsRoute,
  ProfileRoute: ProfileRoute,
  UploadRoute: UploadRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>(); 